
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using NMY;

namespace NMY {
	public class TestSingletonAutogenerated : SingletonStartupBehaviour<TestSingletonAutogenerated>{
		protected override void StartupEnter(){
			Debug.Log(name+" starting up... xx");
			base.StartupEnter();
		}
	}
}
