
using System.Collections;
using UnityEngine;
using NMY;

namespace NMY {
	public class TestSingletonDuplicate : SingletonStartupBehaviour<TestSingletonDuplicate>{
		protected override void StartupEnter(){
			Debug.Log(name+" starting up...");
			base.StartupEnter();

			// Startup Singleton that has not been added to the Testscene and thus will be instantiated during runtime
			TestSingletonAutogenerated.instance.Startup();
		}
	}
}
